### ISSUE TITLE
Erro na minha formataçao do código

### ISSUE THREAD

**Issue by arturgarcia13** [ProfRonan/matrizes-e-vetores-arturgarcia13#2]
oi professor, o senhor poderia me ajudar a finalizar essa atividade?
esta dando um erro de formatação na funçao soma() mas eu nao to conseguindo identificar qual seria.

obrigado pela atenção,

**Comment by SeuRonao** [comment]
Veja o commit mais novo que eu fiz as modificações necessárias. #1
